import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});

const db = new PrismaClient({ adapter });

const features = [
  // MODULE A — Vision To Text
  {
    slug: "image-to-prompt",
    name: "Gambar ke Prompt",
    module: "A",
    creditCost: 0.2,
    category: "Vision AI",
    description: "Ubah gambar menjadi prompt AI detail.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },

  // MODULE B — Standard Editing (1 credit each)
  {
    slug: "remove-bg",
    name: "Hapus Background",
    module: "B",
    creditCost: 1,
    category: "Edit Cepat",
    description: "Menghapus background foto secara akurat.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "retouch",
    name: "AI Retouch",
    module: "B",
    creditCost: 1,
    category: "Edit Cepat",
    description: "Perbaikan kulit dan detail wajah.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "photo-enhance",
    name: "Perbaiki Foto",
    module: "B",
    creditCost: 1,
    category: "Edit Cepat",
    description: "Restorasi foto lama dan buram.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "sketch",
    name: "Sketsa AI",
    module: "B",
    creditCost: 1,
    category: "Creative",
    description: "Konversi foto menjadi sketsa artistik.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "caricature",
    name: "Art & Karikatur",
    module: "B",
    creditCost: 1,
    category: "Creative",
    description: "Foto menjadi gaya artistik unik.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "anime-real",
    name: "Anime To Real",
    module: "B",
    creditCost: 1,
    category: "Creative",
    description: "Mengubah anime menjadi realistis.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "magic-edit",
    name: "AI Edit",
    module: "B",
    creditCost: 1,
    category: "Edit Cepat",
    description: "Edit foto berdasarkan instruksi teks.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "change-angle",
    name: "Ubah Angle",
    module: "B",
    creditCost: 1,
    category: "Edit Cepat",
    description: "Mengubah sudut pandang kamera.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },

  // MODULE C — Multi Reference Generation (3 credits each)
  {
    slug: "photo-merge",
    name: "Gabung Foto",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Gabungkan beberapa foto menjadi satu.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "face-swap",
    name: "Face Swap",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Pertukaran wajah dengan foto referensi.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 3,
    multiImage: true,
    active: true,
  },
  {
    slug: "product-studio",
    name: "Product Studio",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Foto produk studio profesional.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "fashion-ai",
    name: "Fashion AI",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Mockup fashion menggunakan AI.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "mockup",
    name: "Product Mockup",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Tempel desain ke template mockup.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "virtual-tryon",
    name: "Virtual Try On",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Pasangkan pakaian virtual ke model.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 2,
    multiImage: true,
    active: true,
  },
  {
    slug: "pose-change",
    name: "Ubah Pose",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Mengubah pose manusia dalam foto.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 2,
    multiImage: true,
    active: true,
  },
  {
    slug: "passport",
    name: "Pas Foto AI",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Foto formal dokumen standar.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "barber",
    name: "Barber Preview",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Simulasi gaya rambut sebelum potong.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "outpaint",
    name: "Perluas Foto",
    module: "C",
    creditCost: 3,
    category: "Professional",
    description: "Memperluas batas area foto.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "prewedding",
    name: "Pre Wedding AI",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Foto prewedding dengan tema AI.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "couple",
    name: "Potret Cinta",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Foto pasangan natural dan romantis.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "baby",
    name: "Baby Born",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Newborn studio AI yang menggemaskan.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 3,
    multiImage: false,
    active: true,
  },
  {
    slug: "child",
    name: "Foto Anak",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Tema foto anak yang lucu dan natural.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 3,
    multiImage: false,
    active: true,
  },
  {
    slug: "umroh",
    name: "Umroh & Haji",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Foto tema religi dan spiritual.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: false,
    active: true,
  },
  {
    slug: "maternity",
    name: "Maternity",
    module: "C",
    creditCost: 3,
    category: "Special Moments",
    description: "Foto maternity yang indah dan artistik.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 2,
    multiImage: false,
    active: true,
  },

  // MODULE D — Marketing Generation (5 credits each)
  {
    slug: "banner",
    name: "Banner AI",
    module: "D",
    creditCost: 5,
    category: "Marketing",
    description: "Banner promosi hybrid AI generatif.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
  {
    slug: "carousel",
    name: "Carousel Sosmed",
    module: "D",
    creditCost: 5,
    category: "Marketing",
    description: "Carousel Instagram dan TikTok AI.",
    aiModel: "gemini-2.0-flash",
    safetyLevel: 1,
    multiImage: true,
    active: true,
  },
];

async function main() {
  console.log("🌱 Seeding features...");

  for (const feature of features) {
    await db.feature.upsert({
      where: { slug: feature.slug },
      update: feature,
      create: feature,
    });
    console.log(`  ✓ ${feature.name}`);
  }

  console.log(`\n✅ Seeded ${features.length} features successfully!`);
}

main()
  .catch((e) => {
    console.error("❌ Seed failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
